version: 2
jobs:
  test:
  - checkout
  - setup_remote_docker:
      version: 17.09.0-ce
  - run:
      name: Build & Test Image
      command: |
        docker-compose up -d --build
        inspec exec tests -t "docker://terraform-builder"
        docker-compose down

  build_and_deploy:
  - checkout
  - setup_remote_docker:
      version: 17.09.0-ce
  - run:
      name: Build & Test Image
      command: |
        docker-compose up -d --build
        inspec exec tests -t "docker://terraform-builder"
        docker-compose down
  - deploy:
      name: Push Image
      command: |
        docker-compose push builder:latest
        docker-compose push builder:${CIRCLE_BUILD_NUM}

workflows:
  version: 2
  build:
    jobs:
      - test:
          context: org-global
          filters:
            branches:
              ignore:
                - master
      - build_and_deploy:
          context: org-global
          filters:
            branches:
              only:
                - master
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_and_deploy
