version: 2
jobs:
  build:
    docker:
      - image: damacus/docker-builder:latest
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.09.0-ce
      - run:
          name: Build & Test Image
          command: |
            source ./.docker/functions.sh
            build
            docker-compose -f .docker/docker-compose.yaml up -d
            inspec exec tests -t docker://docker_builder_1 --controls=terraform-commands
      - deploy:
          name: Push Image
          command: |
            source ".docker/functions.sh"
            push

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
